### ISSUE TITLE
An news on the new router?

### ISSUE THREAD

**Issue by avstudios** [dart-lang/angular2#107]
Are you working the new router? I had a look at this article and it looks quite well to me. [routing-in-angular-2-revisited](http://blog.thoughtram.io/angular/2016/06/14/routing-in-angular-2-revisited.html). If yes, is there a chance that implement it to the final Angular 2 version? Or maybe  it's possible to start using it now?

**Comment by zoechi** [comment]
In Angular2 TS the router was rebuilt because the previous one didn't work out with lazy loading.
In Dart there were no such issues because of the way lazy loading is implemented in Dart.
AFAIK there are no plans to replace the router.
It was mentioned that Angular2 Dart will support alternative router implementations.

**Comment by avstudios** [comment]
Thanks Günter. I must have missed that information.

**Comment by cporte** [comment]
This was not the only issue with the router if I remember correctly, like easily knowing which route is currently active, access parent parameters in child route, some strange issues with aux routes, and requirements to define all the routes in the same place. Plus, the roadmap mention the router, so I hope there is actually some plan to do something (but probably not a priority)
