### ISSUE TITLE
Will this be kept up to date with Angular2?

### ISSUE THREAD

**Issue by jrote1** [dart-lang/angular2#14]

**Comment by zoechi** [comment]
Would be interesting what the plans are for keeping TS and Dart in sync from API, bug fixes, ...

**Comment by phase** [comment]
From reading some notes from somewhere linked on some subreddit, I have come to believe that there is an AngularDart team, whose job is to keep up to date with Angular.

**Comment by indiealexh** [comment]
As per: http://angularjs.blogspot.co.uk/2016/07/a-dedicated-team-for-angulardart.html

> Both versions will share the same template syntax and, where appropriate, the same API.

> But you'll have the freedom to submit pull requests in the language that you know best, and changes can be made and reviewed without the added burdens of compilation and cross-compatibility to downstream languages.

So I think the goal is to keep them in sync, but there will be some divergence.

**Comment by zoechi** [comment]
I saw that as well, but I guess it would be quite helpful for contributors to know more details. I assume there are many eager to get stuff that already is in TS but not yet in Dart ported, but duplicate work should be avoided.

**Comment by b-strauss** [comment]
This feels like another nail in the coffing for 'Dart for the web'. :(

**Comment by matanlurey** [comment]
Hi all, thanks for bringing up this issue.

This is not meant to be a definitive answer, but I can answers to the best of my ability:

1. Angular 2 TS and Dart will be similar, but *not* the same. As you probably know, lots of patterns that might make sense for one language will make no sense or even conflict with another. We are hoping to maintain the same template syntax and annotations where they make sense, but make no guarantee of 1:1 behavior.

2. Angular Dart is going to be focusing primarily on a few things, instead of supporting as many features or client targets (e.g. web workers, server, browser, react native). Some are:

- **Performance** (Get as close to possible to that sweet sweet 60FPS)
- **Code size** (Make sure applications are tree-shakeable to the max)
- **Super easy dev workflow** (No complicated dependencies, work out of the box with DDC)

Most of all, we want a clear, concise public API that would make both small developers and enterprise applications very comfortable. Our customers internally will benefit immensely and so will you all.

I hope that is helpful and we should have more updates (including a sync to github) soon.
