### ISSUE TITLE
Create e2e tests for common "error" cases and assert good messages

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular2#178]

**Comment by jonahwilliams** [comment]
Two issues with this currently are
  1.  the parser will generate a lot of empty NgText from whitespace, which is a huge pain to deal with in matching.  Need to implement ignoreWhitespace or something similar.
  2.  Still need to set/define equality so that we can make sure the parsed expressions match up as well

**Comment by matanlurey** [comment]
@jonahwilliams We could do implement `ignoreWhitespace`, or write a matcher, i.e.

```dart
expect(parse(someHtml), equalsAngularTemplate([
  ...
], ignoreWhitespace: true);
```

**Comment by jonahwilliams** [comment]
I like the custom matcher, that should be a bit faster / reusable for now
