### ISSUE TITLE
Dart2JS warnings when bind model with inheritance

### ISSUE THREAD

**Issue by wem** [dart-lang/angular2#179]
Hello
We get a lot of Dart2JS warnings because we bind references of model class instances with inheritance in templates. For example:

```
abstract class TileParameterContainer {
   ...
}
class GaugeTileParameterContainer extends TileParameterContainer {
   ...
   String gaugeTitle;
   ...
}

class AddLiveDashboardWizardStep02bComponent extends WizardPageBase
    implements OnInit {
   ...
   TileParameterContainer paramContainer;
   ...
}

<input ... [(ngModel)]="paramContainer.gaugeTitle" ...>
```

#### Dart2JS warning:

> Warning from Dart2JS on trex|web/main.dart:
> packages/trex/trex.template.dart:7213:23:
> The getter 'gaugeTitle' is not defined for the class 'TileParameterContainer'. final currVal_8 = ctx.paramContainer.gaugeTitle;

Are there any drawbacks when use model inheritance for bindings?

Regards

**Comment by hterkelsen** [comment]
Sorry, I don't fully understand what you're asking. You're receiving the warning because `paramContainer` is declared to be a `TileParameterContainer`, a class which doesn't have a `gaugeTitle` getter.

Since `AddLiveDashboardWizardStep02bComponent` will crash if `paramContainer` is not a `GaugeTileParameterContainer`, why not just declare it as `GaugeTileParameterContainer paramContainer;`?
