### ISSUE TITLE
The RouteParams.get function should return a dynamic object

### ISSUE THREAD

**Issue by gchumillas** [dart-lang/angular2#280]
The following function should return a dynamic object:
https://github.com/dart-lang/angular2/blob/master/lib/src/router/instruction.dart#L32

In some circumstances, it returns an Object other than a String.

**Comment by zoechi** [comment]
What circumstances?

**Comment by gchumillas** [comment]
For example:
```dart
final param = {'this': 'is', 'a': 'complex', 'var': 'iable'};
router.navigate(['Section', {'id': sectionId, 'param': param}]);
```

And the following code prints `_InternalLinkedHashMap`, instead of `String`:
```dart
final t = _params.get('param');
print(t.runtimeType);
```

**Comment by zoechi** [comment]
Dart doesn't automatically convert a map like `{'this': 'is', 'a': 'complex', 'var': 'iable'}` between map and String (it might use `toString()` to convert from `param` though).
If you want such an URL then you need to de/serialize `param` from/to JSON or whatever format you want yourself.
The browsers URL bar only takes a string and therefore it doesn't make sense to pass anything else.

**Comment by gchumillas** [comment]
However I think that the 'get' method should throw, at least, an ArgumentError, indicating that the parameter does not conform the required format. In any case, passing parameters other than strings is a great feature.

**Comment by zoechi** [comment]
No, passing parameters other than strings makes no sense.
If you pass a map and it is converted to a string because of its `toString()` implementation, it won't buy you anything, because when someone bookmarks this URL and opens your app using this bookmark you'll get a string and nothing will create a map from that, so sometimes you'll get a map and sometimes a string when you read this parameter.
AFAIR this was changed from dynamic to string a while ago, because this caused confusion already with passing a number which sometimes arrived as string and sometimes as number (this is no biggie in JS/TS but is in Dart).

Yes, I'd also argue for only allowing string to be passed in the first place.

It's not my call though. I'm not a Dart or Angular team member.

**Comment by matanlurey** [comment]
We'll be rolling in a new router, so I'm closing this as _wontfix_.
