### ISSUE TITLE
Update v3 changelog to mention removal of "Title"

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/angular2#304]
Hi,

Angular 3 Dart does not export Title within the browser lib and it is not saying it was removed in the CHANGELOG.

**Comment by kevmoo** [comment]
Absolutely. Will update the changelog.

**Comment by jodinathan** [comment]
How do we change the title within Angular 3?

**Comment by matanlurey** [comment]
Hi @jodinathan - I'll make sure this gets in the next CHANGELOG, it was an oversight.

Because AngularDart only works within the browser, the single best way is simply:

```dart
import 'package:html';

...

document.title = 'Whatever you want';
```

Of course, you are always welcome to keep something like the `Title` service in your application, but for the vast majority of projects this doesn't have any benefit unfortunately.

**Comment by jodinathan** [comment]
@matanlurey, I researched "change title angular 2 dart" and aways got the Title service as the answer. Didn't know it was so simple as a document.title. Laughs.
thanks
