### ISSUE TITLE
Pub get can not find 3.0.0-beta+1

### ISSUE THREAD

**Issue by tfzhu** [dart-lang/angular2#358]
I'm following this tutorial: https://webdev-angular3-dartlang-org.firebaseapp.com/angular/tutorial/toh-pt0

pub get will show error

Package angular2 has no versions that match 3.0.0-beta+1 derived from:
- angular_tour_of_heroes depends on version 3.0.0-beta+1

**Comment by daftspaniel** [comment]
I had the same issue and switching to Dart 1.23.0 fixed it.

The error message is not helpful (actual issue is +1 requires a newer SDK so it can't 'find' a version that matches the current SDK) - believe there is an issue raised on this.

**Comment by kwalrath** [comment]
I'll add something to the docs about requiring 1.23.

**Comment by chalin** [comment]
The version should have been updated to `3.0.0-beta+2`, but the version update script missed the toh-0 pubspec. The pubspec already had 1.23.0 as a minimal version constraint though, so I'm not sure why you didn't first get an error about SDK version mismatch. Anyhow, #570 fixed the toh-0 pubspec.

@matanlurey @kwalrath - this isn't an Angular problem so this issue should be closed (also because the issue has been addressed in the docs -- via #568, and soon via #570).
