### ISSUE TITLE
Regarding beginner friendly Dart webdev resources

### ISSUE THREAD

**Issue by abhi18av** [dart-lang/angular2#362]
Hi angularDart team!!

I must say that I'm a huge fan of your work and please do feel free to close this issue as it's more about having more beginner friendly resources rather than some technical debt.

The thing is, I'd love to build some AngularDart UI and for that I need to know how the entire 

* FIRST priority -> Code and Feedback cycle work, something like live-reload.
This could be added to the generic template menu in IntelliJ dart stagehand package

* SECOND priority -> How exactly am I supposed to use the DDC with the IntelliJ plugin.

* A bit more stress on the AngularDart documentation from the perspective of someone who's getting started with AngularDart itself rather than TypeScript.

**Comment by zoechi** [comment]
There is no live-reload support for Dart web development (currently only Flutter)
There is currently no DDC support for Angular (seems to come with version 4)

**Comment by abhi18av** [comment]
So @zoechi , could something like that demo from Dart Conference be used to achieve the same effect?

https://github.com/vsmenon/dart-jsinterop-quill

**Comment by hentoesch** [comment]
i think, the talk at the conference was a proof of concept that with ddc and regular chrome you can get a development cycle similar to what we have now with dartium and pub serve. 
interaction with dartium from an IDE is not supported by the free intellij community edition, you can do it only with webstorm.
you can always run pub serve from the command line and use dartium/chrome webdev tools.(using regular chrome is WAY slower because there is always a compile step with dart2js included).

**Comment by zoechi** [comment]
@abhi18av with DDC it's not Dartium but plain JS (generated by DDC) with Chrome which does support life reload.
AFAIK with WebStorm/IDEA it doesn't work because Dartium is a few versions behind (perhaps this has changed with updates since I tried a few months ago, but it seems it's not officially supported with Dartium by Jetbrains)

**Comment by matanlurey** [comment]
1. Hot reload is tracking via https://github.com/dart-lang/angular2/issues/160
2. DDC support is planned for `pub` - tracking via https://github.com/dart-lang/angular2/issues/171
3. Please file bugs directly against our documentation if you can: https://github.com/dart-lang/site-webdev
