### ISSUE TITLE
Issue with emulated view encapsulation changes from 2.2.0 to 3.0.0

### ISSUE THREAD

**Issue by sestegra** [dart-lang/angular2#368]
```dart
@Component(
    selector: 'navbar',
    template: '''
        <div *ngFor="let content of contents">
          <navbar-tab [text]="content"></navbar-tab>
        </div>
        ''',
    styles: const [':host .tab-label-content a { color: red; }'],
    directives: const [NavbarTab])
class Navbar {
  Navbar();

  @Input()
  List<String> contents = ["Menu #1", "Menu #2"];
}

@Component(
    selector: 'navbar-tab',
    template: '''<a><span>{{text}}</span></a>''',
    host: const {"style": "display: block;", "class": "tab-label-content"})
class NavbarTab {
  @Input()
  String text;
}

void main() {
  bootstrap(AppComponent);
}
```

NavbarTab is red with angular2 2.2.0.
NavbarTab is black with angular2 3.0.0.

On both versions, DOM outputs are similar (except emulated view encapsulation is done with classes instead of attributes).

```html
<navbar _nghost-vgl-2="">
  <!--template bindings={}-->
  <div _ngcontent-vgl-2="">
    <navbar-tab _ngcontent-vgl-2="" class="tab-label-content" style="display: block;">
      <a><span>Menu #1</span></a>
    </navbar-tab>
  </div>
  <div _ngcontent-vgl-2="">
    <navbar-tab _ngcontent-vgl-2="" class="tab-label-content" style="display: block;">
      <a><span>Menu #2</span></a>
    </navbar-tab>
  </div>
</navbar>
...
```

```html
<navbar class="_nghost-qhq-2">
  <!--template bindings={}-->
  <div class="_ngcontent-qhq-2">
    <navbar-tab style="display: block;" class="tab-label-content _ngcontent-qhq-2">
      <a><span>Menu #1</span></a>
    </navbar-tab>
  </div>
  <div class="_ngcontent-qhq-2">
    <navbar-tab style="display: block;" class="tab-label-content _ngcontent-qhq-2">
      <a><span>Menu #2</span></a>
    </navbar-tab>
  </div>
</navbar>
```

On the other hand, styles are differents
- `<style>[_nghost-vgl-2] .tab-label-content a { color: red; }</style>`
- `<style>._nghost-qhq-2 .tab-label-content._ngcontent-qhq-2 a._ngcontent-qhq-2 { color:red; }</style>
`

See the complete source code here:
https://github.com/sestegra/issue-angulardart

**Comment by leonsenft** [comment]
Hi @sestegra, this is working as intended. Angular has component style encapsulation, meaning selectors you write in one component's stylesheet only apply to itself. This is achieved by adding a component specific class (previously attribute but we found class to be faster) to the elements within a component's template, and shimming its CSS to match.

You're trying to style an element within `NavbarTab`'s template from `Navbar`'s styles. The `a` in `:host .tab-label-content a` belongs to the child component's template.

Now the reason you've seen a change in behavior is because we fixed a bug with `:host`. As you may have noticed from the shimmed styles, previously the selectors following `:host` weren't shimmed, whereas now they are. `:host` exists to serve an entirely difference purpose than piercing component boundaries. Instead you can use the shadow piercing combinator `/deep/` or `>>>` to prevent the remainder of the selector from being scoped.

### Option 1: Use shadow piercing combinator

You can rewrite your selector as

```
.tab-label-content >>> a
```

### Option 2: Use legacy style encapsulation

Alternatively, you can enable legacy style encapsulation in the Angular transformer. We recognized many projects likely depend on this bug as a feature, so you can preserve `:host`'s old behavior by enabling a flag in your _pubspec.yaml_.

```yaml
...
transformers:
  - angular2:
      use_legacy_style_encapsulation: true
...
```

### Option 3: Use a SCSS mixin

If you're at all familiar with [SASS/SCSS](http://sass-lang.com/), you can write a mixin for your child component you wish to style from another component.

```sass
@mixin navbar-tab-anchor-color($color) {
  /deep/ a {
    color: $color;
  }
}
```
_Note SCSS reads `>>>` as three `>` combinators so you must use `/deep/`._

In your parent components SCSS, you can then import and use the mixin.

```sass
.tab-label-content {
  @include navbar-tab-anchor-color(red);
}
```

This approach may seem overly verbose, but it essentially compiles down to the same things as [Option 1](#Option-1) and you have the benefit of controlling how your component is styled externally.

In your case I'd recommend [Option 1](#Option-1), but I wanted to mention [Option 3](#Option-3) as it's ideal in cases for large projects. If you already have an existing project where refactoring styles is prohibitive, [Option 2](#Option-2) is a good fallback.

**Comment by zoechi** [comment]
> (previously attribute but we found class to be faster)

earlier Polymer versions also heavily relied on attributes, but they also found class to be faster, especially on IE AFAIR.
